"use client";\nimport {useEffect} from "react";\nexport default function Home(){useEffect(()=>{let raf=0;const move=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(()=>document.documentElement.style.setProperty("--sy",String(window.scrollY)))};move();addEventListener("scroll",move,{passive:true});return()=>{removeEventListener("scroll",move);cancelAnimationFrame(raf)}},[]);return <main className="cinema">
<header className="cinemaNav"><a href="/" className="brand">MESA/PAGA</a><div><a href="#producto">PRODUCTO</a><a href="#planes">PLANES</a><a className="navPill" href="/registro">EMPEZAR</a></div></header>
<section className="filmHero"><div className="heroGlow"/><div className="parallaxGrid"/><div className="parallaxOrb po1"/><div className="parallaxOrb po2"/><div className="eyebrow">RESTAURANT EXPERIENCE · NFC · QR · PAY</div><h1>TOCA.<br/><i>PAGA.</i><br/>SIGUE.</h1><p>Una nueva capa para el restaurante: menú, cuenta, pago y datos desde la propia mesa.</p><div className="proofRail"><span>01 NFC / QR</span><span>02 CUENTA</span><span>03 PAGO</span><span>04 TICKET</span><span>05 ANALYTICS</span></div><a className="roundCta" href="/t/demo-12">VIVIR<br/>LA DEMO ↗</a><div className="scrollCue">SCROLL TO EXPERIENCE ↓</div></section>
<section className="tapScene" id="producto"><div className="sceneCopy"><span>01 / TOCA</span><h2>UNA MESA.<br/>UN GESTO.</h2><p>El cliente acerca el móvil al NFC o escanea el QR. Sin descargar una app.</p></div><div className="phone"><div className="phoneTop"/><div className="phoneScreen"><small>MESA/PAGA</small><b>MESA 12</b><span>Restaurante Demo</span><div className="tapOrb">NFC</div><em>Cuenta detectada</em></div></div><div className="pulse p1"/><div className="pulse p2"/></section>
<section className="billScene"><div className="bill"><span>RESTAURANTE DEMO · MESA 12</span><h3>Tu cuenta</h3><div><b>2× Menú del día</b><strong>36,00 €</strong></div><div><b>1× Agua</b><strong>2,50 €</strong></div><div><b>2× Café</b><strong>10,00 €</strong></div><hr/><div className="total"><b>TOTAL</b><strong>48,50 €</strong></div><button>PAGAR AHORA →</button></div><div className="giantWords">SIN<br/><i>ESPERAR.</i></div></section>
<section className="paidScene"><span>02 / PAGA · EXPERIENCIA DEMO</span><div className="check">✓</div><h2>48,50 €<br/><i>PAGADO.</i></h2><p>Confirmación segura. Ticket digital. La mesa puede seguir.</p><div className="paidActions">PDF · IMAGEN · COMPARTIR · MENOS PAPEL</div></section>
<section className="menuScene"><div><span>03 / DESCUBRE</span><h2>MENÚ QUE<br/><i>TRABAJA.</i></h2><p>Carta digital, pedidos y disponibilidad. El restaurante decide si activa solo menú, menú + pedido o la experiencia completa.</p></div><div className="menuCards"><article><small>01</small><b>Menú del día</b><em>18,00 €</em></article><article><small>02</small><b>Burger especial</b><em>16,50 €</em></article><article><small>03</small><b>Postres</b><em>7,50 €</em></article></div></section>
<section className="dataScene"><div className="dataIntro"><span>04 / ENTIENDE</span><h2>DE LA MESA<br/>A LA <i>DECISIÓN.</i></h2></div><div className="metrics"><article><small>VENTAS</small><strong>Top platos</strong><p>Qué sale, cuándo y cuánto genera.</p></article><article><small>COCINA</small><strong>Tiempos</strong><p>Pedido → preparación → entrega.</p></article><article><small>MESAS</small><strong>Rotación</strong><p>Servicio, espera y tiempo total.</p></article><article><small>NEGOCIO</small><strong>Margen*</strong><p>Popularidad + velocidad + costes.</p></article></div><small className="dataNote">* El margen requiere costes fiables aportados por el restaurante.</small></section>
<section className="managedScene"><span>05 / MESAPAGA GESTIONADO</span><h2>NO CAMBIES<br/>TU RESTAURANTE.<br/><i>NOSOTROS LO CONECTAMOS.</i></h2><p>Preparamos mesas, NFC y QR, configuramos el panel y conectamos las integraciones compatibles.</p><div className="kit">RECIBE EL KIT → COLÓCALO → EMPIEZA</div></section>
<section className="priceScene" id="planes"><div className="priceHead"><span>PLANES</span><h2>ELIGE TU<br/><i>RITMO.</i></h2></div><div className="priceGrid"><a href="/planes/start"><small>START</small><strong>29€<em>/mes + IVA</em></strong><p>Hasta 15 mesas · NFC + QR · panel · pago total · ticket digital.</p><b>VER START →</b></a><a className="hot" href="/planes/pro"><small>PRO</small><strong>79€<em>/mes + IVA</em></strong><p>Hasta 50 mesas · pagos parciales · Analytics · TPV compatible · soporte prioritario.</p><b>VER PRO →</b></a><a href="/planes/group"><small>GROUP</small><strong>A MEDIDA</strong><p>Multi-restaurante · roles · reporting · integraciones e implantación.</p><b>VER GROUP →</b></a></div><p className="legalMini">Precios B2B. IVA no incluido. Las comisiones del proveedor de pagos se facturan aparte. MESAPAGA no custodia fondos del restaurante ni almacena datos completos de tarjeta.</p></section>
<section className="finalScene"><small>READY?</small><h2>LA CUENTA<br/>YA NO <i>ESPERA.</i></h2><a href="/registro">EMPEZAR PILOTO ↗</a><footer>MESA/PAGA · RESTAURANT OS · 2026</footer></section>
</main>}